import { IoMdCart } from "react-icons/io";
import { BiSolidConversation } from "react-icons/bi";
import { FaCalendar } from "react-icons/fa";
import { FaMoneyBill } from "react-icons/fa6";
import { FaFileContract } from "react-icons/fa";
import { MdInventory2 } from "react-icons/md";
import { MdSpaceDashboard } from "react-icons/md";
import { CiSearch } from "react-icons/ci";
import { MdOutlineKeyboardArrowLeft } from "react-icons/md";
import { MdKeyboardArrowRight } from "react-icons/md";
import { IoIosNotifications } from "react-icons/io";
import { IoMdHelpCircle } from "react-icons/io";
import { IoIosSettings } from "react-icons/io";
import { IoIosLogOut } from "react-icons/io";
import { MdDelete } from "react-icons/md";
import { MdOutlineCloudUpload } from "react-icons/md";
import { FaRegEdit } from "react-icons/fa";

export const Cart = IoMdCart;
export const Chat = BiSolidConversation;
export const Calendar = FaCalendar;
export const Money = FaMoneyBill;
export const Documents = FaFileContract;
export const Inventory = MdInventory2;
export const Dashboard = MdSpaceDashboard;
export const Search = CiSearch;
export const LeftArrow = MdOutlineKeyboardArrowLeft;
export const RightArrow = MdKeyboardArrowRight;
export const Notifications = IoIosNotifications;
export const Help = IoMdHelpCircle;
export const Settings = IoIosSettings;
export const Logout = IoIosLogOut;
export const Delete = MdDelete;
export const Upload = MdOutlineCloudUpload;
export const Edit = FaRegEdit;
